### ISSUE TITLE
Create docker image for Taiko

### ISSUE THREAD

**Issue by zabil** [getgauge-contrib/gauge-docker#1]
Create a docker image with 
* Node js 8+
* Gauge
* Gauge js plugin
* Taiko pre-requiresites for headless chrome

**Comment by sriv** [comment]
https://hub.docker.com/r/getgauge/taiko/ has been created.

Example js-taiko project [Dockerfile](https://github.com/getgauge-examples/js-taiko/blob/master/Dockerfile).
