### ISSUE TITLE
Update Gauge/Taiko/node docker image

### ISSUE THREAD

**Issue by chadlwilson** [getgauge-contrib/gauge-docker#3]
It'd be great to get an updated Taiko dockerfile and regular (automated?) publishing of said images into Docker Hub with appropriate tags and links back to the Dockerfiles.

The current version of this image on Docker Hub has an old version of Gauge, and Taiko 0.2.0 which doesn't appear to be compatible with some of the more recent plugin versions available for Gauge. It also makes using the image a bit laborious, because if you update the built-in Gauge and Taiko yourself it adds several hundred MB to the image size through another layer.

From trying to use this image, I have a few observations
* There are no descriptions or links back to `Dockerfile`s on Docker hub - it'd be good to provide this as is commonly done for other projects that publish images to Docker Hub. I rarely blindly pull something from Docker Hub - I like to know what I am building on (is it alpine-based? Debian based?)
* Taiko is included inside the image, however the general instructions for Taiko installation (and indeed `gauge init js`) will add it as a local `node_module` in your project. This means that when you build on top of this Docker image/`Dockerfile` so that you can run your tests in a CI environment you end up with two Taiko installations and two Chromium installations, making the image huge.

I would suggest that
* this image is deprecated and repurposed to `node.dockerfile` and becomes similar to the other Dockerfiles - it's Gauge with nodejs (but excludes Taiko and Chromium itself)
* multi-stage builds are used to produce multiple Docker images from this file; tagged in some standard way, e.g. 
    * `getgauge/node:latest` - Just nodejs + gauge, for people testing Nodejs services, perhaps
    * `getgauge/node:chrom-dep` - layers on the dependencies to support chrome/chromium
* if we want to get fancy, you could make the node versions explicit
    * `getgauge/node:11`, `getgauge/node:11-chrom-dep` or something like that

Although this is not specific to the Taiko/Node/Chromium image
* some kind of automated process is configured to
    * rebuild and publish images regularly for patching from the base images used
    * republish Docker images automatically for new Gauge versions

**Comment by Apoorva-GA** [comment]
@chadlwilson We are deprecating the taiko docker image as it makes more sense to just pull the base node image and your project may have gauge and taiko as dependencies like below:
```
"dependencies": {
    "@getgauge/cli": "latest",
     "taiko": "latest"
  }
```
and mention the command to execute in the scripts like below:
```
"scripts": {
    "test": "gauge run specs,
}
```
So that you can run the tests using `npm test`.

**Comment by chadlwilson** [comment]
Hi @Apoorva-GA does using a regular `node` base image actually work? My understanding is that there are a number of dependencies that the base image needs in order to be able to run Chromium (headless) hence all the `apt-get`s on [taiko.dockerfile](https://github.com/getgauge-contrib/gauge-docker/blob/master/taiko.dockerfile); and that the purpose of providing such a base image was to ensure you had something that would work out of the box.

**Comment by Apoorva-GA** [comment]
@chadlwilson I think all that we need is headless chrome. Something like 
```
apt-get update &&\
  apt-get install -y git-all gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
    libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 \
    libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
    libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates \
    fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget &&\
    rm -rf /var/lib/apt/lists/*
```
should do for us.
